
modLoader="javafml"
loaderVersion="[36,)"
showAsResourcePack=false
license="GPL-3.0-or-later"

[[mods]]
modId="trophymodaltarpack"
version="0.0.1"
displayName="Trophy Mod"
logoFile="examplemod.png"
credits="Thanks to KaupenJoe for the modding tutorials!"
authors="ChaosDog"
description='''
This mod was developed for KristenStuff's modpack!
'''

[[dependencies.trophymodaltarpack]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.trophymodaltarpack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
